# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- xxxxxxx

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
     gem install jwt

      npm install -g jwt-cli
      
      gh extensions install Link-/gh-token
      
      gh token

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'gh token generate --key $(Build.SourcesDirectory)/samplegithubappmarkcunninghamuk.2022-12-13.private-key.pem  --app_id 271969'


#- task: PowerShell@2
#  inputs:
#    targetType: 'inline'
#    script: 'gh repo create markcunninghamuk/myRepo1 --public'

